### ISSUE TITLE
12. Convert RGB → HEX is not correct

### ISSUE THREAD

**Issue by DanielHemmati** [gigantz/code-like#1]
The code you've written is as follows 

```javascript
const rgb2hex = ([r, g, b]) =>
  `#${(1 << 24) + (r << 16) + (g << 8) + b}`.toString(16).substr(1);

console.log(rgb2hex([76, 11, 181]));
// #4c0bb5
```
Which the desired output is `#4c0bb5` but what we get is `21760949` .   

![it's not correct](https://user-images.githubusercontent.com/25554446/107875418-031de880-6ec0-11eb-9fd9-9d0f9eaf43f5.png)

the correct way of writing the code is as follows 

```javascript 
function rgbToHex(r, g, b) {
  return "#" + ((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1);
}

console.log(rgbToHex(0, 51, 255)); // #0033ff
```
And the reason it works because we are converting the number part to hex.

And also thanks for your awesome code you've share. i learned a lot from them.
Happy Coding! 😃

**Comment by gigantz** [comment]
Hey @danielhemmati,
Yeah, I changed the code after testing it and forgot to separate a part with hex itself 🤦 

Thank you a lot, mate!
Happy coding! 🥳
